USE [master]
GO

/****** Object:  Database [LIVRARIA]    Script Date: 07/03/2020 16:56:04 ******/
CREATE DATABASE [LIVRARIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LIVRARIA', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LIVRARIA.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LIVRARIA_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LIVRARIA_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LIVRARIA] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LIVRARIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LIVRARIA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LIVRARIA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LIVRARIA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LIVRARIA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LIVRARIA] SET ARITHABORT OFF 
GO

ALTER DATABASE [LIVRARIA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LIVRARIA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LIVRARIA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LIVRARIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LIVRARIA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LIVRARIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LIVRARIA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LIVRARIA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LIVRARIA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LIVRARIA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LIVRARIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LIVRARIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LIVRARIA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LIVRARIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LIVRARIA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LIVRARIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LIVRARIA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LIVRARIA] SET RECOVERY FULL 
GO

ALTER DATABASE [LIVRARIA] SET  MULTI_USER 
GO

ALTER DATABASE [LIVRARIA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LIVRARIA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LIVRARIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LIVRARIA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LIVRARIA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LIVRARIA] SET  READ_WRITE 
GO


